// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// ArticleTag is the predicate function for articletag builders.
type ArticleTag func(*sql.Selector)

// Auth is the predicate function for auth builders.
type Auth func(*sql.Selector)

// ReadArticle is the predicate function for readarticle builders.
type ReadArticle func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
