services:
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:14.7-alpine
    ports:
      - 54321:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
  redis:
    container_name: ${APP_NAME}-redis
    image: redis:7.0.9-alpine
    ports:
      - 63791:6379
    restart: always
  firebase:
    container_name: ${APP_NAME}-firebase
    build:
      context: .
      dockerfile: firebase/Dockerfile
    ports:
      - 9091:9099
      - 4001:4000
    volumes:
      - ./firebase:/firebase
    restart: always
  core:
    container_name: ${APP_NAME}-core
    build:
      context: .
      dockerfile: appcore/Dockerfile
    ports:
      - 8081:8080
    environment:
      DOMAIN: http://localhost:8081
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      REDIS_URL: redis:6379
      API_KEY: local
      ENV: ${ENV}
      FIREBASE_SECRET: '{"type": "service_account","project_id": "emulator"}'
      FIREBASE_API_ENDPOINT: http://firebase:9099/identitytoolkit.googleapis.com
      FIREBASE_API_KEY: emulator
      FIREBASE_AUTH_EMULATOR_HOST: firebase:9099
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - postgres
      - redis
      - firebase
  api:
    container_name: ${APP_NAME}-api
    build:
      context: .
      dockerfile: appapi/Dockerfile
    ports:
      - 8082:8080
    environment:
      APP_CORE_URL: http://core:8080
      ENV: ${ENV}
      REDIS_URL: redis:6379
      FIREBASE_SECRET: '{"type": "service_account","project_id": "emulator"}'
      FIREBASE_API_ENDPOINT: http://firebase:9099/identitytoolkit.googleapis.com
      FIREBASE_API_KEY: emulator
      FIREBASE_AUTH_EMULATOR_HOST: firebase:9099
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - core
  db-migration:
    container_name: ${APP_NAME}-db-migration
    build:
      context: .
      dockerfile: migration/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - postgres
