name: diff
run-name: ${{ github.ref_name }} by @${{ github.actor }} [${{ github.workflow }}]
on:
  pull_request:
    paths:
      - .github/workflows/diff.yaml
      - api/**/*.proto
      - "**/*.go"
      - go.mod
      - go.sum
jobs:
  diff:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Set up aqua
        uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.33.0
      - name: Set up backend go tool
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua i
      - name: Generate connect code
        run: buf generate --template ./proto/buf.gen.yaml
      - name: Generate go code
        run: go generate ./...
      - name: Go mod tidy
        run: go mod tidy
      - name: Check diff
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git status --porcelain;
            exit 1;
          else
            echo "no changes";
          fi
