name: unit test
run-name: ${{ github.ref_name }} by @${{ github.actor }} [${{ github.workflow }}]
on:
  pull_request:
    paths:
      - .github/workflows/test.unit.yaml
      - proto/**/*.proto
      - "**/*.go"
      - go.mod
      - go.sum
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Go Test
        run: go test ./internal/...
      - name: coverage
        run: |
          go test ./internal/...  -coverpkg=./... -coverprofile ./coverage.txt
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
