name: yaml lint
run-name: ${{ github.ref_name }} by @${{ github.actor }} [${{ github.workflow }}]
on:
  pull_request:
    paths:
      - "**/*.yaml"
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up aqua
        uses: aquaproj/aqua-installer@v1.2.0
        with:
          aqua_version: v1.25.0
      - name: Set up tool
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua i
      - name: Lint yaml
        run: yamlfmt -lint
